### ISSUE TITLE
关于DVTA的dll劫持测试

### ISSUE THREAD

**Issue by wangtua** [theLSA/CS-checklist#1]
您好，关于DVTA的dll劫持，我在我的本地复现的时候，用procmon去监视其行为，发现DVTA加载version的时候，结果是正常的，并非本文中的name not found。请问是还需要其他配置吗？是不是要重新编译什么的？求教了。

**Comment by theLSA** [comment]
dvta默认是没有version.dll的。
请仔细观察，procmon建议加过滤避免干扰，不需要其他配置或者重新编译。
https://github.com/secvulture/dvta/tree/master/DVTA/DVTA/bin/Release //（没有version.dll哦）
//还有任何问题欢迎反馈！
